name = "htpi"
defaultTargets = ["HTPILib"]

[leanOptions]
linter.unusedVariables = false
linter.unusedTactic = false
pp.funBinderTypes = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "HTPILib"

[[lean_lib]]
name = "StudentWork"
roots = ["Blank", "Chap3Ex", "Chap4Ex", "Chap5Ex", "Chap6Ex", "Chap7Ex", "Chap8Ex"]
